// resources/js/Components/PageHeader.vue
<script setup lang="ts">
defineProps<{ title: string; description?: string; eyebrow?: string }>();
</script>

<template>
    <div class="d-flex flex-wrap ga-4 align-start justify-space-between mb-6">
        <div>
            <div v-if="eyebrow" class="text-overline text-primary font-weight-bold mb-1">{{ eyebrow }}</div>
            <h1 class="text-h4 font-weight-bold mb-2">{{ title }}</h1>
            <p v-if="description" class="text-body-1 text-medium-emphasis mb-0">{{ description }}</p>
        </div>
        <div v-if="$slots.actions" class="d-flex flex-wrap ga-2 align-center">
            <slot name="actions" />
        </div>
    </div>
</template>

// resources/js/Components/PageHeader.tsx
import { ReactNode } from 'react';

type Props = {
    eyebrow?: string;
    title: string;
    description?: string;
    actions?: ReactNode;
};

export default function PageHeader({ eyebrow, title, description, actions }: Props) {
    return (
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
            <div className="max-w-2xl">
                {eyebrow ? <p className="mb-2 text-xs uppercase tracking-[0.35em] text-brand-rose">{eyebrow}</p> : null}
                <h1 className="font-display text-4xl text-stone-900 md:text-5xl">{title}</h1>
                {description ? <p className="mt-3 text-sm leading-7 text-stone-600 md:text-base">{description}</p> : null}
            </div>
            {actions ? <div className="flex flex-wrap items-center gap-3">{actions}</div> : null}
        </div>
    );
}
